# Generated by Django 4.1.6 on 2023-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiMua',
            fields=[
                ('ten', models.CharField(max_length=20)),
                ('makh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('namsinh', models.CharField(max_length=20)),
            ],
        ),
    ]
