# Generated by Django 4.1.6 on 2023-02-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoimua',
            name='token',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
