# Generated by Django 4.1.6 on 2023-02-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0002_nguoimua_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoimua',
            old_name='makh',
            new_name='sdt',
        ),
    ]
